### PR TITLE
John/login signup

### PR DESCRIPTION
**Pull request by johnmarion1126**
## Summary
* Add `login` and `signup` screens
* Add navigation using `react-navigation`
* Add styling for `login` and `signup`

---
(STILL NEEDS TO BE INTEGRATED WITH BACKEND)
* Wrote `createUser` to collect user inputs and send to server 
* Wrote `getUser` to fetch user from server using username

## Screenshots
login
signup

### CODE REVIEW

**Comment by Ritayim** [comment]
I think we should change username in login to sign up since we never ask for a user name

**Comment by johnmarion1126** [comment]
> I think we should change username in login to sign up since we never ask for a user name

So change the username input to full name so it matches the input options in the sign up page? 

I think I did that, but I instead replaced the full name option with username in the sign up page:
```javascript
<TextInput
    placeholder="Enter your username"
    placeholderTextColor="lightgray"
    maxLength={20}
    style={styles.inputs}
    onBlur={Keyboard.dismiss}
    onChangeText={text => handleNameChange(text)}
    value={username}
/>
```

**Comment by Ritayim** [comment]
> 

I think the current authentication of firebase is only supporting email/password sign up, which is why we must sign in with email. There is a workaround but I don't think it's necessary tbh

**Comment by johnmarion1126** [comment]
Ah ok, I'll edit the code so that it just uses email.

**Pull request closed without merging**
